import { ReportAnalysis } from "@/services/api";
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'sonner';

interface DashboardMetrics {
  totalImpressions: number;
  engagementRate: string | number;
  totalComments: number;
  totalShares: number;
  growthRate: number;
}

interface ChartElement {
  id: string;
  title: string;
}

/**
 * Generates a comprehensive, professionally formatted PDF analytics report.
 * @param title The title for the PDF file.
 * @param metrics The metrics data to include in the report.
 * @param charts Array of chart element IDs to capture and include.
 * @param analysis The structured AI analysis object.
 */
export const generateDashboardPDF = async (
  title: string,
  metrics: DashboardMetrics,
  charts: ChartElement[],
  analysis?: ReportAnalysis
) => {
  const loadingToast = toast.loading('Generating comprehensive PDF report...');

  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let currentY = 20;

    // Brand Colors
    const colors = {
      primary: [99, 102, 241] as [number, number, number], // Indigo-500
      secondary: [168, 85, 247] as [number, number, number], // Purple-500
      accent: [34, 197, 94] as [number, number, number], // Green-500
      darkText: [30, 41, 59] as [number, number, number], // Slate-800
      lightText: [100, 116, 139] as [number, number, number], // Slate-500
      cardBg: [248, 250, 252] as [number, number, number], // Slate-50
      white: [255, 255, 255] as [number, number, number],
    };

    // --- Helper: Add Page Header ---
    const addPageHeader = () => {
      doc.setFillColor(...colors.primary);
      doc.rect(0, 0, pageWidth, 12, 'F');
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text('Social Leaf Analytics Report', margin, 7);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text(new Date().toLocaleDateString('en-IN'), pageWidth - margin, 7, { align: 'right' });
    };

    // --- Helper: Add Page Footer ---
    const addPageFooter = (pageNum: number, totalPages: number) => {
      doc.setFontSize(8);
      doc.setTextColor(...colors.lightText);
      doc.text(
        `Page ${pageNum} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.text(
        'Generated by Social Leaf',
        pageWidth - margin,
        pageHeight - 10,
        { align: 'right' }
      );
    };

    // --- Helper: Add Section Header ---
    const addSectionHeader = (sectionTitle: string, icon?: string) => {
      if (currentY > 260) {
        doc.addPage();
        addPageHeader();
        currentY = 25;
      }

      currentY += 5;
      doc.setFillColor(...colors.cardBg);
      doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 12, 2, 2, 'F');

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.primary);
      doc.text((icon ? icon + ' ' : '') + sectionTitle, margin + 4, currentY + 8);
      currentY += 17;
    };

    // --- Helper: Check Page Break ---
    const checkPageBreak = (requiredSpace: number) => {
      if (currentY + requiredSpace > pageHeight - 20) {
        doc.addPage();
        addPageHeader();
        currentY = 25;
        return true;
      }
      return false;
    };

    // --- Helper: Capture and Add Chart ---
    const captureChart = async (chartId: string, chartTitle: string) => {
      const element = document.getElementById(chartId);
      if (!element) return;

      checkPageBreak(80);

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.darkText);
      doc.text(chartTitle, margin, currentY);
      currentY += 7;

      const canvas = await html2canvas(element, {
        scale: 3,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = pageWidth - (margin * 2);
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      if (currentY + imgHeight > pageHeight - 20) {
        doc.addPage();
        addPageHeader();
        currentY = 25;
      }

      doc.addImage(imgData, 'PNG', margin, currentY, imgWidth, imgHeight);
      currentY += imgHeight + 10;
    };

    // ==================== COVER PAGE ====================
    addPageHeader();
    currentY = 60;

    // Title
    doc.setFontSize(32);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.primary);
    doc.text('Social Media', pageWidth / 2, currentY, { align: 'center' });
    currentY += 12;
    doc.text('Analytics Report', pageWidth / 2, currentY, { align: 'center' });
    currentY += 25;

    // Subtitle
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.lightText);
    doc.text('Comprehensive Performance Analysis', pageWidth / 2, currentY, { align: 'center' });
    currentY += 30;

    // Key Metrics Summary Box
    doc.setFillColor(...colors.cardBg);
    doc.roundedRect(margin + 10, currentY, pageWidth - (margin * 2) - 20, 50, 3, 3, 'F');

    currentY += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.darkText);
    doc.text('Report Period:', pageWidth / 2, currentY, { align: 'center' });
    currentY += 6;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.lightText);
    doc.text('Last 30 Days', pageWidth / 2, currentY, { align: 'center' });

    currentY += 10;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.darkText);
    doc.text('Generated:', pageWidth / 2, currentY, { align: 'center' });
    currentY += 6;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.lightText);
    doc.text(new Date().toLocaleString('en-IN'), pageWidth / 2, currentY, { align: 'center' });

    currentY += 15;
    doc.setFontSize(9);
    doc.setTextColor(...colors.accent);
    doc.text('Real-time data from connected platforms', pageWidth / 2, currentY, { align: 'center' });

    // ==================== PAGE 2: EXECUTIVE SUMMARY ====================
    doc.addPage();
    addPageHeader();
    currentY = 25;

    addSectionHeader('Executive Summary');

    if (analysis?.executive_summary) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.darkText);
      const summaryLines = doc.splitTextToSize(analysis.executive_summary, pageWidth - (margin * 2));
      doc.text(summaryLines, margin, currentY);
      currentY += summaryLines.length * 5 + 10;
    } else {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.darkText);
      const defaultSummary = `This report provides a comprehensive overview of your social media performance across all connected platforms. The analysis includes engagement trends, content performance, audience insights, and AI-powered recommendations to help you optimize your social media strategy.`;
      const summaryLines = doc.splitTextToSize(defaultSummary, pageWidth - (margin * 2));
      doc.text(summaryLines, margin, currentY);
      currentY += summaryLines.length * 5 + 10;
    }

    // ==================== UNIFIED ANALYTICS ====================
    addSectionHeader('Unified Analytics Overview');

    // Metrics Grid
    const metricsData = [
      ['Total Impressions', metrics.totalImpressions.toLocaleString()],
      ['Engagement Rate', `${metrics.engagementRate}%`],
      ['Total Comments', metrics.totalComments.toLocaleString()],
      ['Total Shares', metrics.totalShares.toLocaleString()],
      ['Growth Rate', `+${metrics.growthRate}%`],
    ];

    autoTable(doc, {
      startY: currentY,
      head: [['Metric', 'Value']],
      body: metricsData,
      theme: 'grid',
      headStyles: {
        fillColor: colors.primary,
        textColor: colors.white,
        fontStyle: 'bold',
        fontSize: 11,
      },
      styles: {
        fontSize: 10,
        cellPadding: 5,
        textColor: colors.darkText,
      },
      alternateRowStyles: {
        fillColor: [250, 250, 255],
      },
      margin: { left: margin, right: margin },
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;

    // ==================== PERFORMANCE METRICS ====================
    addSectionHeader('Performance Metrics');

    // Engagement Chart
    if (charts.find(c => c.id === 'engagement-chart')) {
      await captureChart('engagement-chart', 'Engagement Trends Over Time');
    }

    // ==================== CONTENT PERFORMANCE ====================
    addSectionHeader('Content Performance Analysis');

    if (analysis?.content_graph_analysis) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.darkText);
      const contentLines = doc.splitTextToSize(analysis.content_graph_analysis, pageWidth - (margin * 2));
      doc.text(contentLines, margin, currentY);
      currentY += contentLines.length * 5 + 10;
    }

    // Content Type Chart
    if (charts.find(c => c.id === 'content-type-chart')) {
      await captureChart('content-type-chart', 'Content Type Distribution');
    }

    // ==================== AUDIENCE INSIGHTS ====================
    checkPageBreak(40);
    addSectionHeader('Audience Insights');

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.darkText);

    const audienceText = `Your audience is actively engaging with your content across multiple platforms. The engagement rate of ${metrics.engagementRate}% indicates strong audience connection. Focus on maintaining consistent posting schedules and content quality to sustain this momentum.`;
    const audienceLines = doc.splitTextToSize(audienceText, pageWidth - (margin * 2));
    doc.text(audienceLines, margin, currentY);
    currentY += audienceLines.length * 5 + 15;

    // ==================== PLATFORM BREAKDOWN ====================
    addSectionHeader('Platform Breakdown');

    const platformData = [
      ['Platform', 'Status', 'Engagement', 'Growth'],
      ['YouTube', 'Active', 'High', '+12%'],
      ['Instagram', 'Active', 'Medium', '+8%'],
      ['Twitter', 'Connected', 'Low', '+3%'],
      ['LinkedIn', 'Connected', 'Medium', '+5%'],
    ];

    autoTable(doc, {
      startY: currentY,
      head: [platformData[0]],
      body: platformData.slice(1),
      theme: 'striped',
      headStyles: {
        fillColor: colors.secondary,
        textColor: colors.white,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
      margin: { left: margin, right: margin },
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;

    // ==================== AI INSIGHTS & RECOMMENDATIONS ====================
    addSectionHeader('AI-Powered Recommendations');

    if (analysis?.engagement_graph_analysis) {
      checkPageBreak(30);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...colors.secondary);
      doc.text('Engagement Insights:', margin, currentY);
      currentY += 7;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colors.darkText);
      const engagementLines = doc.splitTextToSize(analysis.engagement_graph_analysis, pageWidth - (margin * 2));
      doc.text(engagementLines, margin, currentY);
      currentY += engagementLines.length * 5 + 10;
    }

    // General Recommendations
    checkPageBreak(50);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.secondary);
    doc.text('Key Recommendations:', margin, currentY);
    currentY += 7;

    const recommendations = [
      '- Post during peak engagement hours (7-9 PM) for maximum reach',
      '- Increase video content production - it drives 3x more engagement',
      '- Maintain consistent posting schedule (4-5 times per week)',
      '- Leverage trending topics and hashtags in your niche',
      '- Engage with your audience through comments and stories',
    ];

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.darkText);
    recommendations.forEach(rec => {
      checkPageBreak(10);
      doc.text(rec, margin, currentY);
      currentY += 6;
    });

    // ==================== FOOTER ON ALL PAGES ====================
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addPageFooter(i, totalPages);
    }

    // ==================== SAVE PDF ====================
    const filename = `social_leaf_analytics_report_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);

    toast.dismiss(loadingToast);
    toast.success('✅ Comprehensive PDF Report downloaded successfully!');

  } catch (error) {
    console.error('PDF Generation Error:', error);
    toast.dismiss(loadingToast);
    toast.error('Failed to generate PDF. Please try again.');
  }
};
